
if( NOT MING_ROOT )
    set( MING_ROOT /usr/local CACHE PATH "Root directory where the Ming library is installed (MING_ROOT/include contains ming.h)" )
endif( NOT MING_ROOT )

FIND_PATH( MING_INCLUDE_DIR ming.h ${MING_ROOT}/include/ )

FIND_LIBRARY( MING_LIBRARY NAMES libming.a ming PATHS ${MING_ROOT}/lib ) 

IF (MING_INCLUDE_DIR AND MING_LIBRARY)
   SET(MING_FOUND TRUE)
ENDIF (MING_INCLUDE_DIR AND MING_LIBRARY)

IF (MING_FOUND)
   IF (NOT MING_FIND_QUIETLY)
      MESSAGE(STATUS "Found Ming: ${FOO_LIBRARY}")
   ENDIF (NOT MING_FIND_QUIETLY)
ELSE (MING_FOUND)
   IF (MING_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Ming")
   ENDIF (MING_FIND_REQUIRED)
ENDIF (MING_FOUND)
